version: '3.4'

# Default configuration for apps with GUI support
x-gui-app:
  &default-gui-app
  network_mode: "host"
  user: ${user_uid}
  environment:
  - location=${PWD}
  - DISPLAY
  - EPICS_CA_AUTO_ADDR_LIST=NO
  - EPICS_CA_ADDR_LIST=127.255.255.255
  - EPICS_CA_MAX_ARRAY_BYTES=80000000
  security_opt:
  - "apparmor=docker-smurf"
  tty: true
  stdin_open: true

services:
  smurf_server_s%%SLOT_NUMBER%%:
    <<: *default-gui-app
    image: tidair/pysmurf-server:%%PYSMURF_VERSION%%
    container_name: smurf_server_s%%SLOT_NUMBER%%
    volumes:
    - /data:/data
    - /home/${user_name}/.Xauthority:/home/${user_name}/.Xauthority
    - /home/${user_name}/.bash_history:/home/${user_name}/.bash_history
    - ${PWD}/fw:/tmp/fw
    - ${PWD}/rogue:/usr/local/src/rogue
    - ${PWD}/pysmurf:/usr/local/src/pysmurf
    - ${PWD}/pysmurf/docker/server/scripts/start_server.sh:/usr/local/src/pysmurf_utilities/start_server.sh
    - ${PWD}/pysmurf/docker/server/scripts/server_common.sh:/usr/local/src/pysmurf_utilities/server_common.sh
    command: -g -w smurf_server_s%%SLOT_NUMBER%% -S shm-smrf-sp01 -N %%SLOT_NUMBER%% -e smurf_server_s%%SLOT_NUMBER%% %%COMM_ARGS%% ${extra_opts}
    #entrypoint: bash
    logging:
      options:
        tag: smurf_server
  pysmurf_s%%SLOT_NUMBER%%:
    <<: *default-gui-app
    image: tidair/pysmurf-client:%%PYSMURF_VERSION%%
    container_name: pysmurf_s%%SLOT_NUMBER%%
    volumes:
    - /data:/data
    - /home/${user_name}/.Xauthority:/home/${user_name}/.Xauthority
    - /home/${user_name}/.bash_history:/home/${user_name}/.bash_history
    - /home/${user_name}/.ipython:/home/${user_name}/.ipython
    - ${PWD}/pysmurf:/usr/local/src/pysmurf
    command: --epics smurf_server_s%%SLOT_NUMBER%%
    logging:
      options:
        tag: pysmurf
    depends_on:
    - smurf_server_s%%SLOT_NUMBER%%