# Add label 'docker-script' to any change within
# 'docker_scripts' folder or any subfolders
docker-scripts:
  - changed-files:
    - any-glob-to-any-file:
      - docker_scripts/**/*

# Add label 'server-scripts' to any change within
# 'server_scripts' folder or any subfolders
server-scripts:
  - changed-files:
    - any-glob-to-any-file:
      - server_scripts/**/*

# Add label 'repo' to any change to all other files    
repo:
  - changed-files:
    - any-glob-to-any-file:
      - ./*
      - ./.?*
      - .github/**/*