# smurf-server-scripts/docker-compose.yml

# This calls the docker-compose.yml files for each service. This conveinetly
# lets docker use the .env in this folder. Otherwise we would design this to
# call docker-compose in each folder individually.

# Usage
# docker-compose up server_dev to start the development server.
# docker-compose config to see the current config taken from the .env file.

# See Also
# https://confluence.slac.stanford.edu/display/SMuRF/SMuRF+software

# Only 2.X and >3.8 support extends. 
version: '2.2'

services:
  server_prod:
    extends:
      file: server_prod/docker-compose.yml
      service: server_prod
      
  server_dev:
    extends:
      file: server_dev/docker-compose.yml
      service: server_dev

  client_dev:
    extends:
      file: client_dev/docker-compose.yml
      service: client_dev

  client_prod:
    extends:
      file: client_prod/docker-compose.yml
      service: client_prod  

  timing_prod:
    extends:
      file: timing_prod/docker-compose.yml
      service: timing_prod

  timing_dev:
    extends:
      file: timing_dev/docker-compose.yml
      service: timing_dev

  base_prod:
    extends:
      file: base_prod/docker-compose.yml
      service: base_prod

  base_dev:
    extends:
      file: base_dev/docker-compose.yml
      service: base_dev
      
  jupyter:
    extends:
      file: jupyter/docker-compose.yml
      service: jupyter

  gui:
    extends:
      file: gui/docker-compose.yml
      service: gui
