#! /usr/bin/env python3

"""
This is the main executable, which just calls docker.
"""

import os
import argparse
import smurf_docker

def list_dirs():
    """
    List this directory ignoring some files. Each folder should have a
    docker-compose.yml file with one service in it, and that service should
    have the same name as the folder. This should make starting services
    more convenient.
    """

    ignore = ['__pycache__', '.git', 'setup']
    services = []
    for f in os.listdir('.'):
        if os.path.isdir(f) and not f in ignore:
            services.append(f)

    return services

desc = "Script for interacting with one SMuRF carrier at a time. Each SMuRF carrier typically has one cryocard, and two RF cards associated with it. SLAC documentation: https://confluence.slac.stanford.edu/display/SMuRF/SLAC+microresonator+RF+electronics+home. SO documentation: http://simonsobservatory.wikidot.com"

parser = argparse.ArgumentParser(description=desc)
parser.add_argument('command', choices = ['start', 'stop', 'restart', 'logs', 'attach', 'build'])
parser.add_argument('service', choices = list_dirs())

args = parser.parse_args()
service = args.service

if args.command == 'start':
    smurf_docker.start(service)

elif args.command == 'stop':
    smurf_docker.stop(service)

elif args.command == 'restart':
    smurf_docker.restart(service)

elif args.command == 'attach':
    smurf_docker.attach(service)

elif args.command == 'logs':
    smurf_docker.logs(service)

elif args.command == 'build':
    smurf_docker.build(service)
