version: '3.4'

x-gui-app:
  &default-gui-app
  network_mode: "host"
  user: ${user}
  environment:
  - location=${PWD}
  - DISPLAY
  - EPICS_CA_AUTO_ADDR_LIST=NO
  - EPICS_CA_ADDR_LIST=127.255.255.255
  - EPICS_CA_MAX_ARRAY_BYTES=80000000
  security_opt:
  - "apparmor=docker-smurf"
  tty: true
  stdin_open: true

x-smurf-server:
  &smurf-server
  <<: *default-gui-app
  image: tidair/smurf-server:${version}
  container_name: ${server_prefix}${slot}
  volumes:
  - /data:/data
  - ${PWD}/fw:/tmp/fw
  - ${PWD}/rogue:/usr/local/src/rogue
  - ${PWD}/pysmurf:/usr/local/src/pysmurf
  - ${PWD}/pysmurf/docker/server/scripts/start_server.sh:/usr/local/src/pysmurf_utilities/start_server.sh
  - ${PWD}/pysmurf/docker/server/scripts/server_common.sh:/usr/local/src/pysmurf_utilities/server_common.sh
  command: -g -w ${server_prefix}${slot} -S ${shelf_prefix}{crate_id} -N ${slot} -e ${server_prefix}${slot} -c ${comm_type}
  
x-pysmurf:
  &pysmurf
  <<: *default-gui-app
  image: tidair/pysmurf-client:${version}
  container_name: ${client_prefix}${slot}
  volumes:
  - /data:/data
  - ${PWD}/pysmurf:/usr/local/src/pysmurf
  command: --epics ${server_prefix}${slot}
  logging:
    options:
      tag: pysmurf
  depends_on:
  - ${server_prefix}${slot}

services:
  ${server_prefix}2:
    <<: *smurf-server
  ${server_prefix}3:
    <<: *smurf-server
  ${server_prefix}4:
    <<: *smurf-server
  ${server_prefix}5:
    <<: *smurf-server
  ${server_prefix}6:
    <<: *smurf-server
  ${server_prefix}7:
    <<: *smurf-server
  ${client_prefix}2:
    <<: *pysmurf
  ${client_prefix}3:
    <<: *pysmurf
  ${client_prefix}4:
    <<: *pysmurf
  ${client_prefix}5:
    <<: *pysmurf
  ${client_prefix}6:
    <<: *pysmurf
  ${client_prefix}7:
    <<: *pysmurf
