version: '3.7'

services:
  utils:
    container_name: utils
    image: tidair/smurf-rogue:${version}
    user: ${USER}
    network_mode: "host"
    environment:
      - DISPLAY
      - EPICS_CA_AUTO_ADDR_LIST=NO
      - EPICS_CA_ADDR_LIST=127.255.255.255
      - EPICS_CA_MAX_ARRAY_BYTES=80000000
    volumes:
      - /data:/data
    entrypoint: connect_remote_gui.py
    tty: true
    stdin_open: true
