# base_prod/docker-compose.yml
# The base container for other SMuRF images. Also called "utils."
# See Also:
# https://confluence.slac.stanford.edu/display/SMuRF/Software+Versions
# https://github.com/slaclab/smurf-base-docker

version: '2.2'

services:
  base_prod:
    container_name: base_prod
    image: tidair/smurf-base:R1.1.3
    user: ${USER}
    network_mode: "host"
    environment:
      - DISPLAY
      - EPICS_CA_AUTO_ADDR_LIST=NO
      - EPICS_CA_ADDR_LIST=127.255.255.255
      - EPICS_CA_MAX_ARRAY_BYTES=80000000
    volumes:
      - /data:/data
      # Be careful if conda is installed.
      - /home/${USER}:/home/${USER}
    tty: true
    stdin_open: true
