version: '3.7'

services:
  client_jupyter:
    build:
      # The docker image is preferably built with Pysmurf already
      # embedded. If the version in main.json changes, Docker will
      # nicely build another image automatically.
      context: .
      args:
        - version=${version}
    user: ${USER}
    environment:
      - EPICS_CA_AUTO_ADDR_LIST=NO
      - EPICS_CA_ADDR_LIST=127.255.255.255
      - EPICS_CA_MAX_ARRAY_BYTES=80000000
    volumes:
      - /data:/data
      - .jupyter/:/home/${USER}/.jupyter
    ports:
      - 8888:8888
    container_name: client_jupyter
