##############################################################################
## This file is part of 'LCLS2 Common Carrier Core'.
## It is subject to the license terms in the LICENSE.txt file found in the 
## top-level directory of this distribution and at: 
##    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html. 
## No part of 'LCLS2 Common Carrier Core', including this file, 
## may be copied, modified, propagated, or distributed except according to 
## the terms contained in the LICENSE.txt file.
##############################################################################
#schemaversion 3.0.0
#once ApplicationCore.yaml
#include TPG.yaml
#include AmcGenericAdcDacCore.yaml

ApplicationCore: &ApplicationCore 
  class: MMIODev
  description: Application Core
  size: 0x80000000
  ########
  children:
  ########
    ##################################################
    # Add your memory mapped devices here
    ##################################################   
    TPG:
      <<: *TPG
      at:
        offset: 0x00000000
    ##################################################
    AmcGenericAdcDacCore:
      <<: *AmcGenericAdcDacCore
      at:
        offset: 0x01000000
  #########
  Commands:
  #########
    ##################################################
    # Add your top level commands here
    ##################################################
