version: '2.2'
  
services:
  base_dev:
    container_name: base_dev

    # Build using ./Dockerfile
    build:
      context: .
  
    network_mode: "host"
    user: ${USER}
    environment:
      - location=${PWD}
      - DISPLAY
      - EPICS_CA_AUTO_ADDR_LIST=NO
      - EPICS_CA_ADDR_LIST=127.255.255.255
      - EPICS_CA_MAX_ARRAY_BYTES=80000000
    tty: true
    stdin_open: true
