version: '3.7'

x-gui-app:
  &default-gui-app
  network_mode: "host"
  user: 1000:1001
  environment:
  - location=${PWD}
  - DISPLAY
  - EPICS_CA_AUTO_ADDR_LIST=NO
  - EPICS_CA_ADDR_LIST=127.255.255.255
  - EPICS_CA_MAX_ARRAY_BYTES=80000000
  volumes:
  - /data:/data
  tty: true
  stdin_open: true

x-smurf-server:
  &smurf-server
  <<: *default-gui-app
  image: tidair/pysmurf-server:${version}
  container_name: ${server_prefix}${slot}
  command: -S ${crate_prefix}${crate} -N ${slot} -c ${comm_type} --disable-hw-detect --defaults /tmp/fw/smurf_cfg/defaults/defaults_c02_lb_hb.yml
  
x-smurf-client:
  &smurf-client
  <<: *default-gui-app
  image: tidair/pysmurf-client:${version}
  container_name: ${client_prefix}${slot}
  command: --epics ${server_prefix}${slot}
  depends_on:
  - ${server_prefix}${slot}

services:
  smurf_server_s2:
    <<: *smurf-server
  smurf_server_s3:
    <<: *smurf-server
  smurf_server_s4:
    <<: *smurf-server
  smurf_server_s5:
    <<: *smurf-server
  smurf_server_s6:
    <<: *smurf-server
  smurf_server_s7:
    <<: *smurf-server
  smurf_client_s2:
    <<: *smurf-client
  smurf_client_s3:
    <<: *smurf-client
  smurf_client_s4:
    <<: *smurf-client
  smurf_client_s5:
    <<: *smurf-client
  smurf_client_s6:
    <<: *smurf-client
  smurf_client_s7:
    <<: *smurf-client
