version: '3.4'

services:
  tpg_ioc:
    image: tidair/smurf-tpg-ioc:R1.7.3-1.3.0
    container_name: smurf_timing
    # The IOC needs default PVs stored in /data/.
    volumes:
    - /data:/data
    network_mode: "host"
    # Ref https://epics.anl.gov/EpicsDocumentation/AppDevManuals/ChannelAccess/cadoc_4.htm
    environment:
    - location=${PWD}
    - EPICS_CA_ADDR_LIST=172.17.255.255
    security_opt:
    - "apparmor=docker-smurf"
    tty: true
    stdin_open: true
    # -a ip : IP address of the FPGA.
    # e.g. 10.0.2.10N. 2 is the timing crate, N is slot of timing crate.
    # e.g. 10.0.1.10N. 1 is the SMuRF crate, N is slot of SMuRF crate. Not typical.
    command: -a 10.0.2.102
