version: '2.2'

services:
  # The SMuRF timing docker container, which contains the EPICS IOC
  # that boots up the carrier. This does not program the carrier,
  # you'll need ProgramFPGA.bash for that. Contact your nearest SLAC
  # representative. After this is run once, assuming nothing else
  # breaks, the firmware will continue operating even when the docker
  # container and IOC are shut down. You just can't interact with it
  # anymore.
  timing_prod:
    container_name: timing_prod
    # Bash substitution.
    image: tidair/smurf-tpg-ioc:v2
    # Need to access:
    # - 10.0.0.0 network
    # - shm-smrf-sp01 (192 network)
    # - 127.0.0.0 network
    # - 172.0.0.0 network
    network_mode: "host"
    environment:
    - EPICS_CA_ADDR_LIST=172.17.255.255
    # Append to the ENTRYPOINT the IP address of the carrier FPGA.
    # 10.0.2.102 is typically the Timing Crate, slot 2.
    # 10.0.1.102 is typically the SMuRF crate, slot 2.
    command: -a 10.0.1.10${slot}
    tty: true
    stdin_open: true
    volumes:
      - /data:/data
