version: '3.4'

services:
  # The SMuRF timing docker container, which contains the EPICS IOC
  # that boots up the carrier. This does not program the carrier,
  # you'll need ProgramFPGA.bash for that. Contact your nearest SLAC
  # representative. After this is run once, assuming nothing else
  # breaks, the firmware will continue operating even when the docker
  # container and IOC are shut down. You just can't interact with it
  # anymore.
  timing:
    container_name: timing
    # Bash substitution.
    image: tidair/smurf-tpg-ioc:${version}
    # Need to access saved PV variables, otherwise crash.
    volumes:
    - /data:/data
    # Need to access the 10. network, so use "host."
    network_mode: "host"
    environment:
    - EPICS_CA_ADDR_LIST=172.17.255.255
    # Append to the ENTRYPOINT the IP address of the carrier FPGA.
    # 10.0.1.102 is the SMuRF crate itself, slot 2. Not typical.
    # Typically should be 10.0.2.10N, so timing crate, slot N. Any slot works.
    command: -a 10.0.2.102
    tty: true
    stdin_open: true
